-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity compute_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    fm_in_buff_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    fm_in_buff_V_ce0 : OUT STD_LOGIC;
    fm_in_buff_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    fm_in_buff_V_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    fm_in_buff_V_ce1 : OUT STD_LOGIC;
    fm_in_buff_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    fm_out_buff_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    fm_out_buff_V_ce0 : OUT STD_LOGIC;
    fm_out_buff_V_we0 : OUT STD_LOGIC;
    fm_out_buff_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of compute_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv10_2A4 : STD_LOGIC_VECTOR (9 downto 0) := "1010100100";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv8_A9 : STD_LOGIC_VECTOR (7 downto 0) := "10101001";
    constant ap_const_lv8_1A : STD_LOGIC_VECTOR (7 downto 0) := "00011010";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv13_1A : STD_LOGIC_VECTOR (12 downto 0) := "0000000011010";
    constant ap_const_lv7_D : STD_LOGIC_VECTOR (6 downto 0) := "0001101";
    constant ap_const_lv11_D : STD_LOGIC_VECTOR (10 downto 0) := "00000001101";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal indvar_flatten23_reg_144 : STD_LOGIC_VECTOR (9 downto 0);
    signal n_0_reg_155 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten_reg_166 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_0_reg_178 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_0_reg_190 : STD_LOGIC_VECTOR (3 downto 0);
    signal reg_202 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_state5_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_state9_pp0_stage3_iter1 : BOOLEAN;
    signal ap_block_state13_pp0_stage3_iter2 : BOOLEAN;
    signal ap_block_state17_pp0_stage3_iter3 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal icmp_ln52_reg_570 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_570_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_state4_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state8_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_state12_pp0_stage2_iter2 : BOOLEAN;
    signal ap_block_state16_pp0_stage2_iter3 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal icmp_ln52_reg_570_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal reg_207 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state7_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state11_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state15_pp0_stage1_iter3 : BOOLEAN;
    signal ap_block_state19_pp0_stage1_iter4 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln52_reg_570_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal shl_ln_fu_219_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln_reg_560 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln58_fu_227_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln58_reg_565 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln52_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_570_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln52_fu_239_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln52_reg_574 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln53_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_579 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln56_1_fu_257_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln56_1_reg_589 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln203_fu_279_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln203_reg_600 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln56_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln56_reg_606 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_302_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_612 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln56_4_fu_313_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln56_4_reg_617 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln56_7_fu_321_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln56_7_reg_624 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln53_1_fu_329_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln53_1_reg_630 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln203_fu_365_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln203_reg_635 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln203_reg_635_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln203_28_fu_387_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln203_28_reg_640 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln53_fu_398_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln53_reg_650 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln203_6_fu_407_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln203_6_reg_655 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_552_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln203_36_reg_662 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln203_36_reg_662_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln203_36_reg_662_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln203_36_reg_662_pp0_iter4_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal j_fu_416_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_667 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln56_1_fu_421_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln56_1_reg_672 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln56_1_reg_672_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln203_44_fu_428_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln203_44_reg_678 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_31_fu_432_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_31_reg_683 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln57_fu_437_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln57_reg_688 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln57_reg_688_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln203_45_fu_443_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln203_45_reg_694 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_33_fu_447_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_33_reg_699 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln203_5_fu_463_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln203_5_reg_714 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_30_fu_469_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_30_reg_721 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_32_fu_473_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_32_reg_726 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_35_fu_487_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_35_reg_731 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_35_reg_731_pp0_iter3_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_34_fu_510_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln203_34_reg_747 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln203_14_fu_529_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln203_14_reg_763 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_phi_mux_indvar_flatten23_phi_fu_148_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_n_0_phi_fu_159_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_indvar_flatten_phi_fu_170_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_i_0_phi_fu_182_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_j_0_phi_fu_194_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal sext_ln203_16_fu_452_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal sext_ln203_18_fu_456_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln203_fu_492_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln203_17_fu_496_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln203_49_fu_515_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal zext_ln203_47_fu_519_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln203_50_fu_535_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln203_19_fu_539_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal n_fu_245_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln203_fu_279_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln54_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln56_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln56_fu_269_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln56_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln56_mid1_fu_347_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln56_2_fu_335_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln56_5_fu_354_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln56_fu_361_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln58_2_fu_370_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln56_3_fu_341_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln56_6_fu_376_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln56_1_fu_383_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_543_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln203_6_fu_407_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln203_5_fu_463_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln203_15_fu_477_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln203_48_fu_483_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln203_fu_500_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln203_46_fu_506_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln1494_2_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_543_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_543_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_543_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_552_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_552_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_552_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_543_p00 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_543_p20 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_552_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_552_p20 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln203_5_fu_463_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln203_6_fu_407_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln203_fu_279_p00 : STD_LOGIC_VECTOR (7 downto 0);

    component conv_mac_muladd_3kbM IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component conv_mac_muladd_7lbW IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    conv_mac_muladd_3kbM_U33 : component conv_mac_muladd_3kbM
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 3,
        din1_WIDTH => 5,
        din2_WIDTH => 4,
        dout_WIDTH => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_543_p0,
        din1 => grp_fu_543_p1,
        din2 => grp_fu_543_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_543_p3);

    conv_mac_muladd_7lbW_U34 : component conv_mac_muladd_7lbW
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 7,
        din1_WIDTH => 5,
        din2_WIDTH => 4,
        dout_WIDTH => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_552_p0,
        din1 => grp_fu_552_p1,
        din2 => grp_fu_552_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_552_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_0_reg_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i_0_reg_178 <= select_ln56_7_reg_624;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_178 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    indvar_flatten23_reg_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten23_reg_144 <= add_ln52_reg_574;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten23_reg_144 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_166 <= select_ln53_reg_650;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten_reg_166 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    j_0_reg_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                j_0_reg_190 <= j_reg_667;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                j_0_reg_190 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    n_0_reg_155_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                n_0_reg_155 <= select_ln56_1_reg_589;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                n_0_reg_155 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    reg_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln52_reg_570_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                reg_202 <= fm_in_buff_V_q0;
            elsif ((((icmp_ln52_reg_570_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln52_reg_570_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
                reg_202 <= fm_in_buff_V_q1;
            end if; 
        end if;
    end process;

    reg_207_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln52_reg_570_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                reg_207 <= fm_in_buff_V_q1;
            elsif ((((icmp_ln52_reg_570_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln52_reg_570_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((icmp_ln52_reg_570_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
                reg_207 <= fm_in_buff_V_q0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                    add_ln203_28_reg_640(7 downto 1) <= add_ln203_28_fu_387_p2(7 downto 1);
                    add_ln203_reg_635(7 downto 1) <= add_ln203_fu_365_p2(7 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    add_ln203_30_reg_721(12 downto 1) <= add_ln203_30_fu_469_p2(12 downto 1);
                    add_ln203_32_reg_726(12 downto 1) <= add_ln203_32_fu_473_p2(12 downto 1);
                add_ln203_35_reg_731 <= add_ln203_35_fu_487_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                    add_ln203_31_reg_683(12 downto 1) <= add_ln203_31_fu_432_p2(12 downto 1);
                    add_ln203_33_reg_699(12 downto 1) <= add_ln203_33_fu_447_p2(12 downto 1);
                    or_ln57_reg_688(4 downto 1) <= or_ln57_fu_437_p2(4 downto 1);
                    shl_ln56_1_reg_672(4 downto 1) <= shl_ln56_1_fu_421_p3(4 downto 1);
                    zext_ln203_44_reg_678(4 downto 1) <= zext_ln203_44_fu_428_p1(4 downto 1);
                    zext_ln203_45_reg_694(4 downto 1) <= zext_ln203_45_fu_443_p1(4 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                add_ln203_34_reg_747 <= add_ln203_34_fu_510_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln203_35_reg_731_pp0_iter3_reg <= add_ln203_35_reg_731;
                add_ln203_36_reg_662_pp0_iter2_reg <= add_ln203_36_reg_662;
                add_ln203_36_reg_662_pp0_iter3_reg <= add_ln203_36_reg_662_pp0_iter2_reg;
                add_ln203_36_reg_662_pp0_iter4_reg <= add_ln203_36_reg_662_pp0_iter3_reg;
                icmp_ln52_reg_570 <= icmp_ln52_fu_233_p2;
                icmp_ln52_reg_570_pp0_iter1_reg <= icmp_ln52_reg_570;
                icmp_ln52_reg_570_pp0_iter2_reg <= icmp_ln52_reg_570_pp0_iter1_reg;
                icmp_ln52_reg_570_pp0_iter3_reg <= icmp_ln52_reg_570_pp0_iter2_reg;
                icmp_ln52_reg_570_pp0_iter4_reg <= icmp_ln52_reg_570_pp0_iter3_reg;
                    or_ln58_reg_565(4 downto 1) <= or_ln58_fu_227_p2(4 downto 1);
                    shl_ln_reg_560(4 downto 1) <= shl_ln_fu_219_p3(4 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln203_36_reg_662 <= grp_fu_552_p3;
                j_reg_667 <= j_fu_416_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                    add_ln203_reg_635_pp0_iter1_reg(7 downto 1) <= add_ln203_reg_635(7 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln52_reg_574 <= add_ln52_fu_239_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_reg_579 = ap_const_lv1_0) and (icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln53_1_reg_630 <= add_ln53_1_fu_329_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                and_ln56_reg_606 <= and_ln56_fu_296_p2;
                i_reg_612 <= i_fu_302_p2;
                    mul_ln203_reg_600(7 downto 1) <= mul_ln203_fu_279_p2(7 downto 1);
                select_ln56_4_reg_617 <= select_ln56_4_fu_313_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_fu_233_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln53_reg_579 <= icmp_ln53_fu_251_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                    mul_ln203_5_reg_714(12 downto 1) <= mul_ln203_5_fu_463_p2(12 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    mul_ln203_6_reg_655(12 downto 1) <= mul_ln203_6_fu_407_p2(12 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                    or_ln57_reg_688_pp0_iter2_reg(4 downto 1) <= or_ln57_reg_688(4 downto 1);
                    shl_ln56_1_reg_672_pp0_iter2_reg(4 downto 1) <= shl_ln56_1_reg_672(4 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln52_reg_570_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                select_ln203_14_reg_763 <= select_ln203_14_fu_529_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                select_ln53_reg_650 <= select_ln53_fu_398_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_fu_233_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln56_1_reg_589 <= select_ln56_1_fu_257_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                select_ln56_7_reg_624 <= select_ln56_7_fu_321_p3;
            end if;
        end if;
    end process;
    shl_ln_reg_560(0) <= '0';
    or_ln58_reg_565(0) <= '1';
    mul_ln203_reg_600(0) <= '0';
    add_ln203_reg_635(0) <= '0';
    add_ln203_reg_635_pp0_iter1_reg(0) <= '0';
    add_ln203_28_reg_640(0) <= '1';
    mul_ln203_6_reg_655(0) <= '0';
    shl_ln56_1_reg_672(0) <= '0';
    shl_ln56_1_reg_672_pp0_iter2_reg(0) <= '0';
    zext_ln203_44_reg_678(0) <= '0';
    zext_ln203_44_reg_678(12 downto 5) <= "00000000";
    add_ln203_31_reg_683(0) <= '0';
    or_ln57_reg_688(0) <= '1';
    or_ln57_reg_688_pp0_iter2_reg(0) <= '1';
    zext_ln203_45_reg_694(0) <= '1';
    zext_ln203_45_reg_694(12 downto 5) <= "00000000";
    add_ln203_33_reg_699(0) <= '1';
    mul_ln203_5_reg_714(0) <= '0';
    add_ln203_30_reg_721(0) <= '0';
    add_ln203_32_reg_726(0) <= '1';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter4, icmp_ln52_fu_233_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln52_fu_233_p2 = ap_const_lv1_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln52_fu_233_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln203_28_fu_387_p2 <= std_logic_vector(unsigned(zext_ln56_1_fu_383_p1) + unsigned(mul_ln203_reg_600));
    add_ln203_30_fu_469_p2 <= std_logic_vector(unsigned(zext_ln203_44_reg_678) + unsigned(mul_ln203_5_reg_714));
    add_ln203_31_fu_432_p2 <= std_logic_vector(unsigned(zext_ln203_44_fu_428_p1) + unsigned(mul_ln203_6_reg_655));
    add_ln203_32_fu_473_p2 <= std_logic_vector(unsigned(zext_ln203_45_reg_694) + unsigned(mul_ln203_5_reg_714));
    add_ln203_33_fu_447_p2 <= std_logic_vector(unsigned(zext_ln203_45_fu_443_p1) + unsigned(mul_ln203_6_reg_655));
    add_ln203_34_fu_510_p2 <= std_logic_vector(unsigned(zext_ln203_46_fu_506_p1) + unsigned(mul_ln203_5_reg_714));
    add_ln203_35_fu_487_p2 <= std_logic_vector(unsigned(zext_ln203_48_fu_483_p1) + unsigned(mul_ln203_6_reg_655));
    add_ln203_fu_365_p2 <= std_logic_vector(unsigned(zext_ln56_fu_361_p1) + unsigned(mul_ln203_reg_600));
    add_ln52_fu_239_p2 <= std_logic_vector(unsigned(ap_phi_mux_indvar_flatten23_phi_fu_148_p4) + unsigned(ap_const_lv10_1));
    add_ln53_1_fu_329_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_166) + unsigned(ap_const_lv8_1));
    and_ln56_fu_296_p2 <= (xor_ln56_fu_285_p2 and icmp_ln54_fu_290_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state20 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage2_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage3_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage1_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage2_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage3_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage1_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage3_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage2_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage3_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln52_fu_233_p2)
    begin
        if ((icmp_ln52_fu_233_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_i_0_phi_fu_182_p4_assign_proc : process(i_0_reg_178, ap_enable_reg_pp0_iter1, icmp_ln52_reg_570, ap_CS_fsm_pp0_stage0, select_ln56_7_reg_624, ap_block_pp0_stage0)
    begin
        if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_i_0_phi_fu_182_p4 <= select_ln56_7_reg_624;
        else 
            ap_phi_mux_i_0_phi_fu_182_p4 <= i_0_reg_178;
        end if; 
    end process;


    ap_phi_mux_indvar_flatten23_phi_fu_148_p4_assign_proc : process(indvar_flatten23_reg_144, ap_enable_reg_pp0_iter1, icmp_ln52_reg_570, ap_CS_fsm_pp0_stage0, add_ln52_reg_574, ap_block_pp0_stage0)
    begin
        if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_indvar_flatten23_phi_fu_148_p4 <= add_ln52_reg_574;
        else 
            ap_phi_mux_indvar_flatten23_phi_fu_148_p4 <= indvar_flatten23_reg_144;
        end if; 
    end process;


    ap_phi_mux_indvar_flatten_phi_fu_170_p4_assign_proc : process(indvar_flatten_reg_166, ap_enable_reg_pp0_iter1, icmp_ln52_reg_570, ap_CS_fsm_pp0_stage0, select_ln53_reg_650, ap_block_pp0_stage0)
    begin
        if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_indvar_flatten_phi_fu_170_p4 <= select_ln53_reg_650;
        else 
            ap_phi_mux_indvar_flatten_phi_fu_170_p4 <= indvar_flatten_reg_166;
        end if; 
    end process;


    ap_phi_mux_j_0_phi_fu_194_p4_assign_proc : process(j_0_reg_190, ap_enable_reg_pp0_iter1, icmp_ln52_reg_570_pp0_iter1_reg, ap_CS_fsm_pp0_stage1, j_reg_667, ap_block_pp0_stage1)
    begin
        if (((icmp_ln52_reg_570_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_phi_mux_j_0_phi_fu_194_p4 <= j_reg_667;
        else 
            ap_phi_mux_j_0_phi_fu_194_p4 <= j_0_reg_190;
        end if; 
    end process;


    ap_phi_mux_n_0_phi_fu_159_p4_assign_proc : process(n_0_reg_155, ap_enable_reg_pp0_iter1, icmp_ln52_reg_570, ap_CS_fsm_pp0_stage0, select_ln56_1_reg_589, ap_block_pp0_stage0)
    begin
        if (((icmp_ln52_reg_570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_n_0_phi_fu_159_p4 <= select_ln56_1_reg_589;
        else 
            ap_phi_mux_n_0_phi_fu_159_p4 <= n_0_reg_155;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    fm_in_buff_V_address0_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, sext_ln203_18_fu_456_p1, sext_ln203_fu_492_p1, ap_block_pp0_stage3, zext_ln203_47_fu_519_p1, zext_ln203_50_fu_535_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            fm_in_buff_V_address0 <= zext_ln203_50_fu_535_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fm_in_buff_V_address0 <= zext_ln203_47_fu_519_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            fm_in_buff_V_address0 <= sext_ln203_fu_492_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            fm_in_buff_V_address0 <= sext_ln203_18_fu_456_p1(12 - 1 downto 0);
        else 
            fm_in_buff_V_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    fm_in_buff_V_address1_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, sext_ln203_16_fu_452_p1, ap_block_pp0_stage2, sext_ln203_17_fu_496_p1, zext_ln203_49_fu_515_p1, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            fm_in_buff_V_address1 <= zext_ln203_49_fu_515_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            fm_in_buff_V_address1 <= sext_ln203_17_fu_496_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            fm_in_buff_V_address1 <= sext_ln203_16_fu_452_p1(12 - 1 downto 0);
        else 
            fm_in_buff_V_address1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    fm_in_buff_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_enable_reg_pp0_iter1, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            fm_in_buff_V_ce0 <= ap_const_logic_1;
        else 
            fm_in_buff_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    fm_in_buff_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_enable_reg_pp0_iter1, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            fm_in_buff_V_ce1 <= ap_const_logic_1;
        else 
            fm_in_buff_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    fm_out_buff_V_address0 <= sext_ln203_19_fu_539_p1(10 - 1 downto 0);

    fm_out_buff_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
            fm_out_buff_V_ce0 <= ap_const_logic_1;
        else 
            fm_out_buff_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fm_out_buff_V_d0 <= reg_207;

    fm_out_buff_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_enable_reg_pp0_iter4, icmp_ln52_reg_570_pp0_iter4_reg)
    begin
        if (((icmp_ln52_reg_570_pp0_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
            fm_out_buff_V_we0 <= ap_const_logic_1;
        else 
            fm_out_buff_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_213_p2 <= "1" when (signed(reg_202) > signed(reg_207)) else "0";
    grp_fu_543_p0 <= grp_fu_543_p00(3 - 1 downto 0);
    grp_fu_543_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln56_1_fu_257_p3),7));
    grp_fu_543_p1 <= ap_const_lv7_D(5 - 1 downto 0);
    grp_fu_543_p2 <= grp_fu_543_p20(4 - 1 downto 0);
    grp_fu_543_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln56_7_reg_624),7));
    grp_fu_552_p0 <= grp_fu_552_p00(7 - 1 downto 0);
    grp_fu_552_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_543_p3),11));
    grp_fu_552_p1 <= ap_const_lv11_D(5 - 1 downto 0);
    grp_fu_552_p2 <= grp_fu_552_p20(4 - 1 downto 0);
    grp_fu_552_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln56_4_reg_617),11));
    i_fu_302_p2 <= std_logic_vector(unsigned(select_ln56_fu_269_p3) + unsigned(ap_const_lv4_1));
    icmp_ln1494_2_fu_523_p2 <= "1" when (signed(reg_207) > signed(reg_202)) else "0";
    icmp_ln52_fu_233_p2 <= "1" when (ap_phi_mux_indvar_flatten23_phi_fu_148_p4 = ap_const_lv10_2A4) else "0";
    icmp_ln53_fu_251_p2 <= "1" when (ap_phi_mux_indvar_flatten_phi_fu_170_p4 = ap_const_lv8_A9) else "0";
    icmp_ln54_fu_290_p2 <= "1" when (ap_phi_mux_j_0_phi_fu_194_p4 = ap_const_lv4_D) else "0";
    j_fu_416_p2 <= std_logic_vector(unsigned(select_ln56_4_reg_617) + unsigned(ap_const_lv4_1));
    mul_ln203_5_fu_463_p0 <= mul_ln203_5_fu_463_p00(8 - 1 downto 0);
    mul_ln203_5_fu_463_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln203_reg_635_pp0_iter1_reg),13));
    mul_ln203_5_fu_463_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln203_5_fu_463_p0) * unsigned(ap_const_lv13_1A), 13));
    mul_ln203_6_fu_407_p0 <= mul_ln203_6_fu_407_p00(8 - 1 downto 0);
    mul_ln203_6_fu_407_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln203_28_reg_640),13));
    mul_ln203_6_fu_407_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln203_6_fu_407_p0) * unsigned(ap_const_lv13_1A), 13));
    mul_ln203_fu_279_p0 <= mul_ln203_fu_279_p00(3 - 1 downto 0);
    mul_ln203_fu_279_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln56_1_reg_589),8));
    mul_ln203_fu_279_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln203_fu_279_p0) * unsigned(ap_const_lv8_1A), 8));
    n_fu_245_p2 <= std_logic_vector(unsigned(ap_phi_mux_n_0_phi_fu_159_p4) + unsigned(ap_const_lv3_1));
    or_ln56_fu_308_p2 <= (icmp_ln53_reg_579 or and_ln56_fu_296_p2);
    or_ln57_fu_437_p2 <= (shl_ln56_1_fu_421_p3 or ap_const_lv5_1);
    or_ln58_2_fu_370_p2 <= (shl_ln56_mid1_fu_347_p3 or ap_const_lv5_1);
    or_ln58_fu_227_p2 <= (shl_ln_fu_219_p3 or ap_const_lv5_1);
    select_ln203_14_fu_529_p3 <= 
        add_ln203_34_reg_747 when (icmp_ln1494_2_fu_523_p2(0) = '1') else 
        add_ln203_35_reg_731_pp0_iter3_reg;
    select_ln203_15_fu_477_p3 <= 
        shl_ln56_1_reg_672 when (grp_fu_213_p2(0) = '1') else 
        or_ln57_reg_688;
    select_ln203_fu_500_p3 <= 
        shl_ln56_1_reg_672_pp0_iter2_reg when (grp_fu_213_p2(0) = '1') else 
        or_ln57_reg_688_pp0_iter2_reg;
    select_ln53_fu_398_p3 <= 
        ap_const_lv8_1 when (icmp_ln53_reg_579(0) = '1') else 
        add_ln53_1_reg_630;
    select_ln56_1_fu_257_p3 <= 
        n_fu_245_p2 when (icmp_ln53_fu_251_p2(0) = '1') else 
        ap_phi_mux_n_0_phi_fu_159_p4;
    select_ln56_2_fu_335_p3 <= 
        ap_const_lv5_0 when (icmp_ln53_reg_579(0) = '1') else 
        shl_ln_reg_560;
    select_ln56_3_fu_341_p3 <= 
        ap_const_lv5_1 when (icmp_ln53_reg_579(0) = '1') else 
        or_ln58_reg_565;
    select_ln56_4_fu_313_p3 <= 
        ap_const_lv4_0 when (or_ln56_fu_308_p2(0) = '1') else 
        ap_phi_mux_j_0_phi_fu_194_p4;
    select_ln56_5_fu_354_p3 <= 
        shl_ln56_mid1_fu_347_p3 when (and_ln56_reg_606(0) = '1') else 
        select_ln56_2_fu_335_p3;
    select_ln56_6_fu_376_p3 <= 
        or_ln58_2_fu_370_p2 when (and_ln56_reg_606(0) = '1') else 
        select_ln56_3_fu_341_p3;
    select_ln56_7_fu_321_p3 <= 
        i_fu_302_p2 when (and_ln56_fu_296_p2(0) = '1') else 
        select_ln56_fu_269_p3;
    select_ln56_fu_269_p3 <= 
        ap_const_lv4_0 when (icmp_ln53_reg_579(0) = '1') else 
        i_0_reg_178;
        sext_ln203_16_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln203_31_reg_683),64));

        sext_ln203_17_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln203_32_reg_726),64));

        sext_ln203_18_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln203_33_reg_699),64));

        sext_ln203_19_fu_539_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln203_36_reg_662_pp0_iter4_reg),64));

        sext_ln203_fu_492_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln203_30_reg_721),64));

    shl_ln56_1_fu_421_p3 <= (select_ln56_4_reg_617 & ap_const_lv1_0);
    shl_ln56_mid1_fu_347_p3 <= (i_reg_612 & ap_const_lv1_0);
    shl_ln_fu_219_p3 <= (ap_phi_mux_i_0_phi_fu_182_p4 & ap_const_lv1_0);
    xor_ln56_fu_285_p2 <= (icmp_ln53_reg_579 xor ap_const_lv1_1);
    zext_ln203_44_fu_428_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln56_1_fu_421_p3),13));
    zext_ln203_45_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln57_fu_437_p2),13));
    zext_ln203_46_fu_506_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln203_fu_500_p3),13));
    zext_ln203_47_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln203_34_reg_747),64));
    zext_ln203_48_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln203_15_fu_477_p3),13));
    zext_ln203_49_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln203_35_reg_731),64));
    zext_ln203_50_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln203_14_reg_763),64));
    zext_ln56_1_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln56_6_fu_376_p3),8));
    zext_ln56_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln56_5_fu_354_p3),8));
end behav;
