// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module compute_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fm_in_buff_V_address0,
        fm_in_buff_V_ce0,
        fm_in_buff_V_q0,
        fm_in_buff_V_address1,
        fm_in_buff_V_ce1,
        fm_in_buff_V_q1,
        fm_out_buff_V_address0,
        fm_out_buff_V_ce0,
        fm_out_buff_V_we0,
        fm_out_buff_V_d0
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_pp0_stage0 = 6'd2;
parameter    ap_ST_fsm_pp0_stage1 = 6'd4;
parameter    ap_ST_fsm_pp0_stage2 = 6'd8;
parameter    ap_ST_fsm_pp0_stage3 = 6'd16;
parameter    ap_ST_fsm_state20 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] fm_in_buff_V_address0;
output   fm_in_buff_V_ce0;
input  [15:0] fm_in_buff_V_q0;
output  [11:0] fm_in_buff_V_address1;
output   fm_in_buff_V_ce1;
input  [15:0] fm_in_buff_V_q1;
output  [9:0] fm_out_buff_V_address0;
output   fm_out_buff_V_ce0;
output   fm_out_buff_V_we0;
output  [15:0] fm_out_buff_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[11:0] fm_in_buff_V_address0;
reg fm_in_buff_V_ce0;
reg[11:0] fm_in_buff_V_address1;
reg fm_in_buff_V_ce1;
reg fm_out_buff_V_ce0;
reg fm_out_buff_V_we0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] indvar_flatten23_reg_144;
reg   [2:0] n_0_reg_155;
reg   [7:0] indvar_flatten_reg_166;
reg   [3:0] i_0_reg_178;
reg   [3:0] j_0_reg_190;
reg   [15:0] reg_202;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state5_pp0_stage3_iter0;
wire    ap_block_state9_pp0_stage3_iter1;
wire    ap_block_state13_pp0_stage3_iter2;
wire    ap_block_state17_pp0_stage3_iter3;
wire    ap_block_pp0_stage3_11001;
reg   [0:0] icmp_ln52_reg_570;
reg   [0:0] icmp_ln52_reg_570_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_state4_pp0_stage2_iter0;
wire    ap_block_state8_pp0_stage2_iter1;
wire    ap_block_state12_pp0_stage2_iter2;
wire    ap_block_state16_pp0_stage2_iter3;
wire    ap_block_pp0_stage2_11001;
reg   [0:0] icmp_ln52_reg_570_pp0_iter2_reg;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state10_pp0_stage0_iter2;
wire    ap_block_state14_pp0_stage0_iter3;
wire    ap_block_state18_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] reg_207;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state7_pp0_stage1_iter1;
wire    ap_block_state11_pp0_stage1_iter2;
wire    ap_block_state15_pp0_stage1_iter3;
wire    ap_block_state19_pp0_stage1_iter4;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln52_reg_570_pp0_iter3_reg;
reg    ap_enable_reg_pp0_iter4;
wire   [4:0] shl_ln_fu_219_p3;
reg   [4:0] shl_ln_reg_560;
wire   [4:0] or_ln58_fu_227_p2;
reg   [4:0] or_ln58_reg_565;
wire   [0:0] icmp_ln52_fu_233_p2;
reg   [0:0] icmp_ln52_reg_570_pp0_iter4_reg;
wire   [9:0] add_ln52_fu_239_p2;
reg   [9:0] add_ln52_reg_574;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln53_fu_251_p2;
reg   [0:0] icmp_ln53_reg_579;
wire   [2:0] select_ln56_1_fu_257_p3;
reg   [2:0] select_ln56_1_reg_589;
wire   [7:0] mul_ln203_fu_279_p2;
reg   [7:0] mul_ln203_reg_600;
wire   [0:0] and_ln56_fu_296_p2;
reg   [0:0] and_ln56_reg_606;
wire   [3:0] i_fu_302_p2;
reg   [3:0] i_reg_612;
wire   [3:0] select_ln56_4_fu_313_p3;
reg   [3:0] select_ln56_4_reg_617;
wire   [3:0] select_ln56_7_fu_321_p3;
reg   [3:0] select_ln56_7_reg_624;
wire   [7:0] add_ln53_1_fu_329_p2;
reg   [7:0] add_ln53_1_reg_630;
wire   [7:0] add_ln203_fu_365_p2;
reg   [7:0] add_ln203_reg_635;
reg   [7:0] add_ln203_reg_635_pp0_iter1_reg;
wire   [7:0] add_ln203_28_fu_387_p2;
reg   [7:0] add_ln203_28_reg_640;
wire   [7:0] select_ln53_fu_398_p3;
reg   [7:0] select_ln53_reg_650;
wire   [12:0] mul_ln203_6_fu_407_p2;
reg   [12:0] mul_ln203_6_reg_655;
wire   [10:0] grp_fu_552_p3;
reg   [10:0] add_ln203_36_reg_662;
reg   [10:0] add_ln203_36_reg_662_pp0_iter2_reg;
reg   [10:0] add_ln203_36_reg_662_pp0_iter3_reg;
reg   [10:0] add_ln203_36_reg_662_pp0_iter4_reg;
wire   [3:0] j_fu_416_p2;
reg   [3:0] j_reg_667;
wire   [4:0] shl_ln56_1_fu_421_p3;
reg   [4:0] shl_ln56_1_reg_672;
reg   [4:0] shl_ln56_1_reg_672_pp0_iter2_reg;
wire   [12:0] zext_ln203_44_fu_428_p1;
reg   [12:0] zext_ln203_44_reg_678;
wire   [12:0] add_ln203_31_fu_432_p2;
reg   [12:0] add_ln203_31_reg_683;
wire   [4:0] or_ln57_fu_437_p2;
reg   [4:0] or_ln57_reg_688;
reg   [4:0] or_ln57_reg_688_pp0_iter2_reg;
wire   [12:0] zext_ln203_45_fu_443_p1;
reg   [12:0] zext_ln203_45_reg_694;
wire   [12:0] add_ln203_33_fu_447_p2;
reg   [12:0] add_ln203_33_reg_699;
wire   [12:0] mul_ln203_5_fu_463_p2;
reg   [12:0] mul_ln203_5_reg_714;
wire   [12:0] add_ln203_30_fu_469_p2;
reg   [12:0] add_ln203_30_reg_721;
wire   [12:0] add_ln203_32_fu_473_p2;
reg   [12:0] add_ln203_32_reg_726;
wire   [12:0] add_ln203_35_fu_487_p2;
reg   [12:0] add_ln203_35_reg_731;
reg   [12:0] add_ln203_35_reg_731_pp0_iter3_reg;
wire   [12:0] add_ln203_34_fu_510_p2;
reg   [12:0] add_ln203_34_reg_747;
wire   [12:0] select_ln203_14_fu_529_p3;
reg   [12:0] select_ln203_14_reg_763;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage1_subdone;
reg   [9:0] ap_phi_mux_indvar_flatten23_phi_fu_148_p4;
wire    ap_block_pp0_stage0;
reg   [2:0] ap_phi_mux_n_0_phi_fu_159_p4;
reg   [7:0] ap_phi_mux_indvar_flatten_phi_fu_170_p4;
reg   [3:0] ap_phi_mux_i_0_phi_fu_182_p4;
reg   [3:0] ap_phi_mux_j_0_phi_fu_194_p4;
wire    ap_block_pp0_stage1;
wire  signed [63:0] sext_ln203_16_fu_452_p1;
wire    ap_block_pp0_stage2;
wire  signed [63:0] sext_ln203_18_fu_456_p1;
wire  signed [63:0] sext_ln203_fu_492_p1;
wire  signed [63:0] sext_ln203_17_fu_496_p1;
wire   [63:0] zext_ln203_49_fu_515_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln203_47_fu_519_p1;
wire   [63:0] zext_ln203_50_fu_535_p1;
wire  signed [63:0] sext_ln203_19_fu_539_p1;
wire   [2:0] n_fu_245_p2;
wire   [2:0] mul_ln203_fu_279_p0;
wire   [0:0] icmp_ln54_fu_290_p2;
wire   [0:0] xor_ln56_fu_285_p2;
wire   [3:0] select_ln56_fu_269_p3;
wire   [0:0] or_ln56_fu_308_p2;
wire   [4:0] shl_ln56_mid1_fu_347_p3;
wire   [4:0] select_ln56_2_fu_335_p3;
wire   [4:0] select_ln56_5_fu_354_p3;
wire   [7:0] zext_ln56_fu_361_p1;
wire   [4:0] or_ln58_2_fu_370_p2;
wire   [4:0] select_ln56_3_fu_341_p3;
wire   [4:0] select_ln56_6_fu_376_p3;
wire   [7:0] zext_ln56_1_fu_383_p1;
wire   [6:0] grp_fu_543_p3;
wire   [7:0] mul_ln203_6_fu_407_p0;
wire   [7:0] mul_ln203_5_fu_463_p0;
wire   [0:0] grp_fu_213_p2;
wire   [4:0] select_ln203_15_fu_477_p3;
wire   [12:0] zext_ln203_48_fu_483_p1;
wire   [4:0] select_ln203_fu_500_p3;
wire   [12:0] zext_ln203_46_fu_506_p1;
wire   [0:0] icmp_ln1494_2_fu_523_p2;
wire   [2:0] grp_fu_543_p0;
wire   [4:0] grp_fu_543_p1;
wire   [3:0] grp_fu_543_p2;
wire   [6:0] grp_fu_552_p0;
wire   [4:0] grp_fu_552_p1;
wire   [3:0] grp_fu_552_p2;
wire    ap_CS_fsm_state20;
reg   [5:0] ap_NS_fsm;
wire    ap_block_pp0_stage2_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [6:0] grp_fu_543_p00;
wire   [6:0] grp_fu_543_p20;
wire   [10:0] grp_fu_552_p00;
wire   [10:0] grp_fu_552_p20;
wire   [12:0] mul_ln203_5_fu_463_p00;
wire   [12:0] mul_ln203_6_fu_407_p00;
wire   [7:0] mul_ln203_fu_279_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

conv_mac_muladd_3kbM #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
conv_mac_muladd_3kbM_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_543_p0),
    .din1(grp_fu_543_p1),
    .din2(grp_fu_543_p2),
    .ce(1'b1),
    .dout(grp_fu_543_p3)
);

conv_mac_muladd_7lbW #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
conv_mac_muladd_7lbW_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_552_p0),
    .din1(grp_fu_552_p1),
    .din2(grp_fu_552_p2),
    .ce(1'b1),
    .dout(grp_fu_552_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_0_reg_178 <= select_ln56_7_reg_624;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_178 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten23_reg_144 <= add_ln52_reg_574;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten23_reg_144 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_166 <= select_ln53_reg_650;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_166 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        j_0_reg_190 <= j_reg_667;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_0_reg_190 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        n_0_reg_155 <= select_ln56_1_reg_589;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        n_0_reg_155 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln52_reg_570_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reg_202 <= fm_in_buff_V_q0;
    end else if ((((icmp_ln52_reg_570_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln52_reg_570_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_202 <= fm_in_buff_V_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln52_reg_570_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reg_207 <= fm_in_buff_V_q1;
    end else if ((((icmp_ln52_reg_570_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln52_reg_570_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln52_reg_570_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        reg_207 <= fm_in_buff_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln52_reg_570 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln203_28_reg_640[7 : 1] <= add_ln203_28_fu_387_p2[7 : 1];
        add_ln203_reg_635[7 : 1] <= add_ln203_fu_365_p2[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln203_30_reg_721[12 : 1] <= add_ln203_30_fu_469_p2[12 : 1];
        add_ln203_32_reg_726[12 : 1] <= add_ln203_32_fu_473_p2[12 : 1];
        add_ln203_35_reg_731 <= add_ln203_35_fu_487_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln203_31_reg_683[12 : 1] <= add_ln203_31_fu_432_p2[12 : 1];
        add_ln203_33_reg_699[12 : 1] <= add_ln203_33_fu_447_p2[12 : 1];
        or_ln57_reg_688[4 : 1] <= or_ln57_fu_437_p2[4 : 1];
        shl_ln56_1_reg_672[4 : 1] <= shl_ln56_1_fu_421_p3[4 : 1];
        zext_ln203_44_reg_678[4 : 1] <= zext_ln203_44_fu_428_p1[4 : 1];
        zext_ln203_45_reg_694[4 : 1] <= zext_ln203_45_fu_443_p1[4 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln203_34_reg_747 <= add_ln203_34_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln203_35_reg_731_pp0_iter3_reg <= add_ln203_35_reg_731;
        add_ln203_36_reg_662_pp0_iter2_reg <= add_ln203_36_reg_662;
        add_ln203_36_reg_662_pp0_iter3_reg <= add_ln203_36_reg_662_pp0_iter2_reg;
        add_ln203_36_reg_662_pp0_iter4_reg <= add_ln203_36_reg_662_pp0_iter3_reg;
        icmp_ln52_reg_570 <= icmp_ln52_fu_233_p2;
        icmp_ln52_reg_570_pp0_iter1_reg <= icmp_ln52_reg_570;
        icmp_ln52_reg_570_pp0_iter2_reg <= icmp_ln52_reg_570_pp0_iter1_reg;
        icmp_ln52_reg_570_pp0_iter3_reg <= icmp_ln52_reg_570_pp0_iter2_reg;
        icmp_ln52_reg_570_pp0_iter4_reg <= icmp_ln52_reg_570_pp0_iter3_reg;
        or_ln58_reg_565[4 : 1] <= or_ln58_fu_227_p2[4 : 1];
        shl_ln_reg_560[4 : 1] <= shl_ln_fu_219_p3[4 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln203_36_reg_662 <= grp_fu_552_p3;
        j_reg_667 <= j_fu_416_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln203_reg_635_pp0_iter1_reg[7 : 1] <= add_ln203_reg_635[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln52_reg_574 <= add_ln52_fu_239_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_reg_579 == 1'd0) & (icmp_ln52_reg_570 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln53_1_reg_630 <= add_ln53_1_fu_329_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        and_ln56_reg_606 <= and_ln56_fu_296_p2;
        i_reg_612 <= i_fu_302_p2;
        mul_ln203_reg_600[7 : 1] <= mul_ln203_fu_279_p2[7 : 1];
        select_ln56_4_reg_617 <= select_ln56_4_fu_313_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_fu_233_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln53_reg_579 <= icmp_ln53_fu_251_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul_ln203_5_reg_714[12 : 1] <= mul_ln203_5_fu_463_p2[12 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln203_6_reg_655[12 : 1] <= mul_ln203_6_fu_407_p2[12 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        or_ln57_reg_688_pp0_iter2_reg[4 : 1] <= or_ln57_reg_688[4 : 1];
        shl_ln56_1_reg_672_pp0_iter2_reg[4 : 1] <= shl_ln56_1_reg_672[4 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln52_reg_570_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        select_ln203_14_reg_763 <= select_ln203_14_fu_529_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        select_ln53_reg_650 <= select_ln53_fu_398_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_fu_233_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln56_1_reg_589 <= select_ln56_1_fu_257_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        select_ln56_7_reg_624 <= select_ln56_7_fu_321_p3;
    end
end

always @ (*) begin
    if ((icmp_ln52_fu_233_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_i_0_phi_fu_182_p4 = select_ln56_7_reg_624;
    end else begin
        ap_phi_mux_i_0_phi_fu_182_p4 = i_0_reg_178;
    end
end

always @ (*) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_indvar_flatten23_phi_fu_148_p4 = add_ln52_reg_574;
    end else begin
        ap_phi_mux_indvar_flatten23_phi_fu_148_p4 = indvar_flatten23_reg_144;
    end
end

always @ (*) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_indvar_flatten_phi_fu_170_p4 = select_ln53_reg_650;
    end else begin
        ap_phi_mux_indvar_flatten_phi_fu_170_p4 = indvar_flatten_reg_166;
    end
end

always @ (*) begin
    if (((icmp_ln52_reg_570_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_mux_j_0_phi_fu_194_p4 = j_reg_667;
    end else begin
        ap_phi_mux_j_0_phi_fu_194_p4 = j_0_reg_190;
    end
end

always @ (*) begin
    if (((icmp_ln52_reg_570 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_n_0_phi_fu_159_p4 = select_ln56_1_reg_589;
    end else begin
        ap_phi_mux_n_0_phi_fu_159_p4 = n_0_reg_155;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        fm_in_buff_V_address0 = zext_ln203_50_fu_535_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fm_in_buff_V_address0 = zext_ln203_47_fu_519_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fm_in_buff_V_address0 = sext_ln203_fu_492_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        fm_in_buff_V_address0 = sext_ln203_18_fu_456_p1;
    end else begin
        fm_in_buff_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        fm_in_buff_V_address1 = zext_ln203_49_fu_515_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fm_in_buff_V_address1 = sext_ln203_17_fu_496_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        fm_in_buff_V_address1 = sext_ln203_16_fu_452_p1;
    end else begin
        fm_in_buff_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        fm_in_buff_V_ce0 = 1'b1;
    end else begin
        fm_in_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        fm_in_buff_V_ce1 = 1'b1;
    end else begin
        fm_in_buff_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        fm_out_buff_V_ce0 = 1'b1;
    end else begin
        fm_out_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln52_reg_570_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        fm_out_buff_V_we0 = 1'b1;
    end else begin
        fm_out_buff_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln52_fu_233_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln52_fu_233_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln203_28_fu_387_p2 = (zext_ln56_1_fu_383_p1 + mul_ln203_reg_600);

assign add_ln203_30_fu_469_p2 = (zext_ln203_44_reg_678 + mul_ln203_5_reg_714);

assign add_ln203_31_fu_432_p2 = (zext_ln203_44_fu_428_p1 + mul_ln203_6_reg_655);

assign add_ln203_32_fu_473_p2 = (zext_ln203_45_reg_694 + mul_ln203_5_reg_714);

assign add_ln203_33_fu_447_p2 = (zext_ln203_45_fu_443_p1 + mul_ln203_6_reg_655);

assign add_ln203_34_fu_510_p2 = (zext_ln203_46_fu_506_p1 + mul_ln203_5_reg_714);

assign add_ln203_35_fu_487_p2 = (zext_ln203_48_fu_483_p1 + mul_ln203_6_reg_655);

assign add_ln203_fu_365_p2 = (zext_ln56_fu_361_p1 + mul_ln203_reg_600);

assign add_ln52_fu_239_p2 = (ap_phi_mux_indvar_flatten23_phi_fu_148_p4 + 10'd1);

assign add_ln53_1_fu_329_p2 = (indvar_flatten_reg_166 + 8'd1);

assign and_ln56_fu_296_p2 = (xor_ln56_fu_285_p2 & icmp_ln54_fu_290_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign fm_out_buff_V_address0 = sext_ln203_19_fu_539_p1;

assign fm_out_buff_V_d0 = reg_207;

assign grp_fu_213_p2 = (($signed(reg_202) > $signed(reg_207)) ? 1'b1 : 1'b0);

assign grp_fu_543_p0 = grp_fu_543_p00;

assign grp_fu_543_p00 = select_ln56_1_fu_257_p3;

assign grp_fu_543_p1 = 7'd13;

assign grp_fu_543_p2 = grp_fu_543_p20;

assign grp_fu_543_p20 = select_ln56_7_reg_624;

assign grp_fu_552_p0 = grp_fu_552_p00;

assign grp_fu_552_p00 = grp_fu_543_p3;

assign grp_fu_552_p1 = 11'd13;

assign grp_fu_552_p2 = grp_fu_552_p20;

assign grp_fu_552_p20 = select_ln56_4_reg_617;

assign i_fu_302_p2 = (select_ln56_fu_269_p3 + 4'd1);

assign icmp_ln1494_2_fu_523_p2 = (($signed(reg_207) > $signed(reg_202)) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_233_p2 = ((ap_phi_mux_indvar_flatten23_phi_fu_148_p4 == 10'd676) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_251_p2 = ((ap_phi_mux_indvar_flatten_phi_fu_170_p4 == 8'd169) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_290_p2 = ((ap_phi_mux_j_0_phi_fu_194_p4 == 4'd13) ? 1'b1 : 1'b0);

assign j_fu_416_p2 = (select_ln56_4_reg_617 + 4'd1);

assign mul_ln203_5_fu_463_p0 = mul_ln203_5_fu_463_p00;

assign mul_ln203_5_fu_463_p00 = add_ln203_reg_635_pp0_iter1_reg;

assign mul_ln203_5_fu_463_p2 = (mul_ln203_5_fu_463_p0 * $signed('h1A));

assign mul_ln203_6_fu_407_p0 = mul_ln203_6_fu_407_p00;

assign mul_ln203_6_fu_407_p00 = add_ln203_28_reg_640;

assign mul_ln203_6_fu_407_p2 = (mul_ln203_6_fu_407_p0 * $signed('h1A));

assign mul_ln203_fu_279_p0 = mul_ln203_fu_279_p00;

assign mul_ln203_fu_279_p00 = select_ln56_1_reg_589;

assign mul_ln203_fu_279_p2 = (mul_ln203_fu_279_p0 * $signed('h1A));

assign n_fu_245_p2 = (ap_phi_mux_n_0_phi_fu_159_p4 + 3'd1);

assign or_ln56_fu_308_p2 = (icmp_ln53_reg_579 | and_ln56_fu_296_p2);

assign or_ln57_fu_437_p2 = (shl_ln56_1_fu_421_p3 | 5'd1);

assign or_ln58_2_fu_370_p2 = (shl_ln56_mid1_fu_347_p3 | 5'd1);

assign or_ln58_fu_227_p2 = (shl_ln_fu_219_p3 | 5'd1);

assign select_ln203_14_fu_529_p3 = ((icmp_ln1494_2_fu_523_p2[0:0] === 1'b1) ? add_ln203_34_reg_747 : add_ln203_35_reg_731_pp0_iter3_reg);

assign select_ln203_15_fu_477_p3 = ((grp_fu_213_p2[0:0] === 1'b1) ? shl_ln56_1_reg_672 : or_ln57_reg_688);

assign select_ln203_fu_500_p3 = ((grp_fu_213_p2[0:0] === 1'b1) ? shl_ln56_1_reg_672_pp0_iter2_reg : or_ln57_reg_688_pp0_iter2_reg);

assign select_ln53_fu_398_p3 = ((icmp_ln53_reg_579[0:0] === 1'b1) ? 8'd1 : add_ln53_1_reg_630);

assign select_ln56_1_fu_257_p3 = ((icmp_ln53_fu_251_p2[0:0] === 1'b1) ? n_fu_245_p2 : ap_phi_mux_n_0_phi_fu_159_p4);

assign select_ln56_2_fu_335_p3 = ((icmp_ln53_reg_579[0:0] === 1'b1) ? 5'd0 : shl_ln_reg_560);

assign select_ln56_3_fu_341_p3 = ((icmp_ln53_reg_579[0:0] === 1'b1) ? 5'd1 : or_ln58_reg_565);

assign select_ln56_4_fu_313_p3 = ((or_ln56_fu_308_p2[0:0] === 1'b1) ? 4'd0 : ap_phi_mux_j_0_phi_fu_194_p4);

assign select_ln56_5_fu_354_p3 = ((and_ln56_reg_606[0:0] === 1'b1) ? shl_ln56_mid1_fu_347_p3 : select_ln56_2_fu_335_p3);

assign select_ln56_6_fu_376_p3 = ((and_ln56_reg_606[0:0] === 1'b1) ? or_ln58_2_fu_370_p2 : select_ln56_3_fu_341_p3);

assign select_ln56_7_fu_321_p3 = ((and_ln56_fu_296_p2[0:0] === 1'b1) ? i_fu_302_p2 : select_ln56_fu_269_p3);

assign select_ln56_fu_269_p3 = ((icmp_ln53_reg_579[0:0] === 1'b1) ? 4'd0 : i_0_reg_178);

assign sext_ln203_16_fu_452_p1 = $signed(add_ln203_31_reg_683);

assign sext_ln203_17_fu_496_p1 = $signed(add_ln203_32_reg_726);

assign sext_ln203_18_fu_456_p1 = $signed(add_ln203_33_reg_699);

assign sext_ln203_19_fu_539_p1 = $signed(add_ln203_36_reg_662_pp0_iter4_reg);

assign sext_ln203_fu_492_p1 = $signed(add_ln203_30_reg_721);

assign shl_ln56_1_fu_421_p3 = {{select_ln56_4_reg_617}, {1'd0}};

assign shl_ln56_mid1_fu_347_p3 = {{i_reg_612}, {1'd0}};

assign shl_ln_fu_219_p3 = {{ap_phi_mux_i_0_phi_fu_182_p4}, {1'd0}};

assign xor_ln56_fu_285_p2 = (icmp_ln53_reg_579 ^ 1'd1);

assign zext_ln203_44_fu_428_p1 = shl_ln56_1_fu_421_p3;

assign zext_ln203_45_fu_443_p1 = or_ln57_fu_437_p2;

assign zext_ln203_46_fu_506_p1 = select_ln203_fu_500_p3;

assign zext_ln203_47_fu_519_p1 = add_ln203_34_reg_747;

assign zext_ln203_48_fu_483_p1 = select_ln203_15_fu_477_p3;

assign zext_ln203_49_fu_515_p1 = add_ln203_35_reg_731;

assign zext_ln203_50_fu_535_p1 = select_ln203_14_reg_763;

assign zext_ln56_1_fu_383_p1 = select_ln56_6_fu_376_p3;

assign zext_ln56_fu_361_p1 = select_ln56_5_fu_354_p3;

always @ (posedge ap_clk) begin
    shl_ln_reg_560[0] <= 1'b0;
    or_ln58_reg_565[0] <= 1'b1;
    mul_ln203_reg_600[0] <= 1'b0;
    add_ln203_reg_635[0] <= 1'b0;
    add_ln203_reg_635_pp0_iter1_reg[0] <= 1'b0;
    add_ln203_28_reg_640[0] <= 1'b1;
    mul_ln203_6_reg_655[0] <= 1'b0;
    shl_ln56_1_reg_672[0] <= 1'b0;
    shl_ln56_1_reg_672_pp0_iter2_reg[0] <= 1'b0;
    zext_ln203_44_reg_678[0] <= 1'b0;
    zext_ln203_44_reg_678[12:5] <= 8'b00000000;
    add_ln203_31_reg_683[0] <= 1'b0;
    or_ln57_reg_688[0] <= 1'b1;
    or_ln57_reg_688_pp0_iter2_reg[0] <= 1'b1;
    zext_ln203_45_reg_694[0] <= 1'b1;
    zext_ln203_45_reg_694[12:5] <= 8'b00000000;
    add_ln203_33_reg_699[0] <= 1'b1;
    mul_ln203_5_reg_714[0] <= 1'b0;
    add_ln203_30_reg_721[0] <= 1'b0;
    add_ln203_32_reg_726[0] <= 1'b1;
end

endmodule //compute_2
