// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module maxpool (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_in_V_AWVALID,
        m_axi_in_V_AWREADY,
        m_axi_in_V_AWADDR,
        m_axi_in_V_AWID,
        m_axi_in_V_AWLEN,
        m_axi_in_V_AWSIZE,
        m_axi_in_V_AWBURST,
        m_axi_in_V_AWLOCK,
        m_axi_in_V_AWCACHE,
        m_axi_in_V_AWPROT,
        m_axi_in_V_AWQOS,
        m_axi_in_V_AWREGION,
        m_axi_in_V_AWUSER,
        m_axi_in_V_WVALID,
        m_axi_in_V_WREADY,
        m_axi_in_V_WDATA,
        m_axi_in_V_WSTRB,
        m_axi_in_V_WLAST,
        m_axi_in_V_WID,
        m_axi_in_V_WUSER,
        m_axi_in_V_ARVALID,
        m_axi_in_V_ARREADY,
        m_axi_in_V_ARADDR,
        m_axi_in_V_ARID,
        m_axi_in_V_ARLEN,
        m_axi_in_V_ARSIZE,
        m_axi_in_V_ARBURST,
        m_axi_in_V_ARLOCK,
        m_axi_in_V_ARCACHE,
        m_axi_in_V_ARPROT,
        m_axi_in_V_ARQOS,
        m_axi_in_V_ARREGION,
        m_axi_in_V_ARUSER,
        m_axi_in_V_RVALID,
        m_axi_in_V_RREADY,
        m_axi_in_V_RDATA,
        m_axi_in_V_RLAST,
        m_axi_in_V_RID,
        m_axi_in_V_RUSER,
        m_axi_in_V_RRESP,
        m_axi_in_V_BVALID,
        m_axi_in_V_BREADY,
        m_axi_in_V_BRESP,
        m_axi_in_V_BID,
        m_axi_in_V_BUSER,
        in_V_offset,
        out_V_offset,
        ch,
        h
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_in_V_AWVALID;
input   m_axi_in_V_AWREADY;
output  [31:0] m_axi_in_V_AWADDR;
output  [0:0] m_axi_in_V_AWID;
output  [31:0] m_axi_in_V_AWLEN;
output  [2:0] m_axi_in_V_AWSIZE;
output  [1:0] m_axi_in_V_AWBURST;
output  [1:0] m_axi_in_V_AWLOCK;
output  [3:0] m_axi_in_V_AWCACHE;
output  [2:0] m_axi_in_V_AWPROT;
output  [3:0] m_axi_in_V_AWQOS;
output  [3:0] m_axi_in_V_AWREGION;
output  [0:0] m_axi_in_V_AWUSER;
output   m_axi_in_V_WVALID;
input   m_axi_in_V_WREADY;
output  [15:0] m_axi_in_V_WDATA;
output  [1:0] m_axi_in_V_WSTRB;
output   m_axi_in_V_WLAST;
output  [0:0] m_axi_in_V_WID;
output  [0:0] m_axi_in_V_WUSER;
output   m_axi_in_V_ARVALID;
input   m_axi_in_V_ARREADY;
output  [31:0] m_axi_in_V_ARADDR;
output  [0:0] m_axi_in_V_ARID;
output  [31:0] m_axi_in_V_ARLEN;
output  [2:0] m_axi_in_V_ARSIZE;
output  [1:0] m_axi_in_V_ARBURST;
output  [1:0] m_axi_in_V_ARLOCK;
output  [3:0] m_axi_in_V_ARCACHE;
output  [2:0] m_axi_in_V_ARPROT;
output  [3:0] m_axi_in_V_ARQOS;
output  [3:0] m_axi_in_V_ARREGION;
output  [0:0] m_axi_in_V_ARUSER;
input   m_axi_in_V_RVALID;
output   m_axi_in_V_RREADY;
input  [15:0] m_axi_in_V_RDATA;
input   m_axi_in_V_RLAST;
input  [0:0] m_axi_in_V_RID;
input  [0:0] m_axi_in_V_RUSER;
input  [1:0] m_axi_in_V_RRESP;
input   m_axi_in_V_BVALID;
output   m_axi_in_V_BREADY;
input  [1:0] m_axi_in_V_BRESP;
input  [0:0] m_axi_in_V_BID;
input  [0:0] m_axi_in_V_BUSER;
input  [30:0] in_V_offset;
input  [30:0] out_V_offset;
input  [31:0] ch;
input  [31:0] h;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_in_V_AWVALID;
reg m_axi_in_V_WVALID;
reg m_axi_in_V_ARVALID;
reg m_axi_in_V_RREADY;
reg m_axi_in_V_BREADY;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] tmp_reg_294;
reg   [30:0] lshr_ln79_1_reg_299;
reg   [30:0] lshr_ln79_2_reg_304;
wire   [15:0] trunc_ln81_fu_206_p1;
reg   [15:0] trunc_ln81_reg_309;
wire   [31:0] select_ln79_fu_222_p3;
reg   [31:0] select_ln79_reg_315;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state5;
wire   [15:0] size_fu_229_p1;
reg   [15:0] size_reg_336;
reg   [13:0] trunc_ln6_reg_341;
wire   [15:0] n_fu_261_p2;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln79_fu_256_p2;
wire   [15:0] i_fu_276_p2;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln80_fu_271_p2;
wire   [15:0] j_fu_282_p2;
reg   [15:0] j_reg_365;
wire    ap_CS_fsm_state12;
reg   [11:0] fm_in_buff_V_address0;
reg    fm_in_buff_V_ce0;
reg    fm_in_buff_V_we0;
wire   [15:0] fm_in_buff_V_q0;
reg    fm_in_buff_V_ce1;
wire   [15:0] fm_in_buff_V_q1;
reg   [9:0] fm_out_buff_V_address0;
reg    fm_out_buff_V_ce0;
reg    fm_out_buff_V_we0;
wire   [15:0] fm_out_buff_V_q0;
wire    grp_store_output_2_fu_128_ap_start;
wire    grp_store_output_2_fu_128_ap_done;
wire    grp_store_output_2_fu_128_ap_idle;
wire    grp_store_output_2_fu_128_ap_ready;
wire    grp_store_output_2_fu_128_m_axi_out_V_AWVALID;
wire   [31:0] grp_store_output_2_fu_128_m_axi_out_V_AWADDR;
wire   [0:0] grp_store_output_2_fu_128_m_axi_out_V_AWID;
wire   [31:0] grp_store_output_2_fu_128_m_axi_out_V_AWLEN;
wire   [2:0] grp_store_output_2_fu_128_m_axi_out_V_AWSIZE;
wire   [1:0] grp_store_output_2_fu_128_m_axi_out_V_AWBURST;
wire   [1:0] grp_store_output_2_fu_128_m_axi_out_V_AWLOCK;
wire   [3:0] grp_store_output_2_fu_128_m_axi_out_V_AWCACHE;
wire   [2:0] grp_store_output_2_fu_128_m_axi_out_V_AWPROT;
wire   [3:0] grp_store_output_2_fu_128_m_axi_out_V_AWQOS;
wire   [3:0] grp_store_output_2_fu_128_m_axi_out_V_AWREGION;
wire   [0:0] grp_store_output_2_fu_128_m_axi_out_V_AWUSER;
wire    grp_store_output_2_fu_128_m_axi_out_V_WVALID;
wire   [15:0] grp_store_output_2_fu_128_m_axi_out_V_WDATA;
wire   [1:0] grp_store_output_2_fu_128_m_axi_out_V_WSTRB;
wire    grp_store_output_2_fu_128_m_axi_out_V_WLAST;
wire   [0:0] grp_store_output_2_fu_128_m_axi_out_V_WID;
wire   [0:0] grp_store_output_2_fu_128_m_axi_out_V_WUSER;
wire    grp_store_output_2_fu_128_m_axi_out_V_ARVALID;
wire   [31:0] grp_store_output_2_fu_128_m_axi_out_V_ARADDR;
wire   [0:0] grp_store_output_2_fu_128_m_axi_out_V_ARID;
wire   [31:0] grp_store_output_2_fu_128_m_axi_out_V_ARLEN;
wire   [2:0] grp_store_output_2_fu_128_m_axi_out_V_ARSIZE;
wire   [1:0] grp_store_output_2_fu_128_m_axi_out_V_ARBURST;
wire   [1:0] grp_store_output_2_fu_128_m_axi_out_V_ARLOCK;
wire   [3:0] grp_store_output_2_fu_128_m_axi_out_V_ARCACHE;
wire   [2:0] grp_store_output_2_fu_128_m_axi_out_V_ARPROT;
wire   [3:0] grp_store_output_2_fu_128_m_axi_out_V_ARQOS;
wire   [3:0] grp_store_output_2_fu_128_m_axi_out_V_ARREGION;
wire   [0:0] grp_store_output_2_fu_128_m_axi_out_V_ARUSER;
wire    grp_store_output_2_fu_128_m_axi_out_V_RREADY;
wire    grp_store_output_2_fu_128_m_axi_out_V_BREADY;
wire   [9:0] grp_store_output_2_fu_128_fm_out_buff_V_address0;
wire    grp_store_output_2_fu_128_fm_out_buff_V_ce0;
wire    grp_load_input_2_fu_144_ap_start;
wire    grp_load_input_2_fu_144_ap_done;
wire    grp_load_input_2_fu_144_ap_idle;
wire    grp_load_input_2_fu_144_ap_ready;
wire    grp_load_input_2_fu_144_m_axi_in_V_AWVALID;
wire   [31:0] grp_load_input_2_fu_144_m_axi_in_V_AWADDR;
wire   [0:0] grp_load_input_2_fu_144_m_axi_in_V_AWID;
wire   [31:0] grp_load_input_2_fu_144_m_axi_in_V_AWLEN;
wire   [2:0] grp_load_input_2_fu_144_m_axi_in_V_AWSIZE;
wire   [1:0] grp_load_input_2_fu_144_m_axi_in_V_AWBURST;
wire   [1:0] grp_load_input_2_fu_144_m_axi_in_V_AWLOCK;
wire   [3:0] grp_load_input_2_fu_144_m_axi_in_V_AWCACHE;
wire   [2:0] grp_load_input_2_fu_144_m_axi_in_V_AWPROT;
wire   [3:0] grp_load_input_2_fu_144_m_axi_in_V_AWQOS;
wire   [3:0] grp_load_input_2_fu_144_m_axi_in_V_AWREGION;
wire   [0:0] grp_load_input_2_fu_144_m_axi_in_V_AWUSER;
wire    grp_load_input_2_fu_144_m_axi_in_V_WVALID;
wire   [15:0] grp_load_input_2_fu_144_m_axi_in_V_WDATA;
wire   [1:0] grp_load_input_2_fu_144_m_axi_in_V_WSTRB;
wire    grp_load_input_2_fu_144_m_axi_in_V_WLAST;
wire   [0:0] grp_load_input_2_fu_144_m_axi_in_V_WID;
wire   [0:0] grp_load_input_2_fu_144_m_axi_in_V_WUSER;
wire    grp_load_input_2_fu_144_m_axi_in_V_ARVALID;
wire   [31:0] grp_load_input_2_fu_144_m_axi_in_V_ARADDR;
wire   [0:0] grp_load_input_2_fu_144_m_axi_in_V_ARID;
wire   [31:0] grp_load_input_2_fu_144_m_axi_in_V_ARLEN;
wire   [2:0] grp_load_input_2_fu_144_m_axi_in_V_ARSIZE;
wire   [1:0] grp_load_input_2_fu_144_m_axi_in_V_ARBURST;
wire   [1:0] grp_load_input_2_fu_144_m_axi_in_V_ARLOCK;
wire   [3:0] grp_load_input_2_fu_144_m_axi_in_V_ARCACHE;
wire   [2:0] grp_load_input_2_fu_144_m_axi_in_V_ARPROT;
wire   [3:0] grp_load_input_2_fu_144_m_axi_in_V_ARQOS;
wire   [3:0] grp_load_input_2_fu_144_m_axi_in_V_ARREGION;
wire   [0:0] grp_load_input_2_fu_144_m_axi_in_V_ARUSER;
wire    grp_load_input_2_fu_144_m_axi_in_V_RREADY;
wire    grp_load_input_2_fu_144_m_axi_in_V_BREADY;
wire   [11:0] grp_load_input_2_fu_144_fm_in_buff_V_address0;
wire    grp_load_input_2_fu_144_fm_in_buff_V_ce0;
wire    grp_load_input_2_fu_144_fm_in_buff_V_we0;
wire   [15:0] grp_load_input_2_fu_144_fm_in_buff_V_d0;
wire    grp_compute_2_fu_160_ap_start;
wire    grp_compute_2_fu_160_ap_done;
wire    grp_compute_2_fu_160_ap_idle;
wire    grp_compute_2_fu_160_ap_ready;
wire   [11:0] grp_compute_2_fu_160_fm_in_buff_V_address0;
wire    grp_compute_2_fu_160_fm_in_buff_V_ce0;
wire   [11:0] grp_compute_2_fu_160_fm_in_buff_V_address1;
wire    grp_compute_2_fu_160_fm_in_buff_V_ce1;
wire   [9:0] grp_compute_2_fu_160_fm_out_buff_V_address0;
wire    grp_compute_2_fu_160_fm_out_buff_V_ce0;
wire    grp_compute_2_fu_160_fm_out_buff_V_we0;
wire   [15:0] grp_compute_2_fu_160_fm_out_buff_V_d0;
reg   [15:0] n_0_reg_92;
reg   [15:0] i_0_reg_104;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln78_fu_247_p2;
reg   [15:0] j_0_reg_116;
wire    ap_CS_fsm_state13;
reg    grp_store_output_2_fu_128_ap_start_reg;
reg    grp_load_input_2_fu_144_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_compute_2_fu_160_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire  signed [31:0] tmp_fu_172_p1;
wire  signed [31:0] sub_ln79_fu_180_p1;
wire   [31:0] sub_ln79_fu_180_p2;
wire  signed [31:0] lshr_ln79_2_fu_196_p1;
wire  signed [31:0] trunc_ln81_fu_206_p0;
wire   [31:0] zext_ln79_1_fu_210_p1;
wire   [31:0] sub_ln79_1_fu_213_p2;
wire   [31:0] zext_ln79_2_fu_219_p1;
wire   [31:0] grp_fu_166_p2;
wire   [31:0] zext_ln78_fu_243_p1;
wire   [31:0] zext_ln79_fu_252_p1;
wire   [31:0] zext_ln80_fu_267_p1;
reg   [12:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 grp_store_output_2_fu_128_ap_start_reg = 1'b0;
#0 grp_load_input_2_fu_144_ap_start_reg = 1'b0;
#0 grp_compute_2_fu_160_ap_start_reg = 1'b0;
end

maxpool_fm_in_bufrcU #(
    .DataWidth( 16 ),
    .AddressRange( 2704 ),
    .AddressWidth( 12 ))
fm_in_buff_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fm_in_buff_V_address0),
    .ce0(fm_in_buff_V_ce0),
    .we0(fm_in_buff_V_we0),
    .d0(grp_load_input_2_fu_144_fm_in_buff_V_d0),
    .q0(fm_in_buff_V_q0),
    .address1(grp_compute_2_fu_160_fm_in_buff_V_address1),
    .ce1(fm_in_buff_V_ce1),
    .q1(fm_in_buff_V_q1)
);

maxpool_fm_out_busc4 #(
    .DataWidth( 16 ),
    .AddressRange( 676 ),
    .AddressWidth( 10 ))
fm_out_buff_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fm_out_buff_V_address0),
    .ce0(fm_out_buff_V_ce0),
    .we0(fm_out_buff_V_we0),
    .d0(grp_compute_2_fu_160_fm_out_buff_V_d0),
    .q0(fm_out_buff_V_q0)
);

store_output_2 grp_store_output_2_fu_128(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_output_2_fu_128_ap_start),
    .ap_done(grp_store_output_2_fu_128_ap_done),
    .ap_idle(grp_store_output_2_fu_128_ap_idle),
    .ap_ready(grp_store_output_2_fu_128_ap_ready),
    .m_axi_out_V_AWVALID(grp_store_output_2_fu_128_m_axi_out_V_AWVALID),
    .m_axi_out_V_AWREADY(m_axi_in_V_AWREADY),
    .m_axi_out_V_AWADDR(grp_store_output_2_fu_128_m_axi_out_V_AWADDR),
    .m_axi_out_V_AWID(grp_store_output_2_fu_128_m_axi_out_V_AWID),
    .m_axi_out_V_AWLEN(grp_store_output_2_fu_128_m_axi_out_V_AWLEN),
    .m_axi_out_V_AWSIZE(grp_store_output_2_fu_128_m_axi_out_V_AWSIZE),
    .m_axi_out_V_AWBURST(grp_store_output_2_fu_128_m_axi_out_V_AWBURST),
    .m_axi_out_V_AWLOCK(grp_store_output_2_fu_128_m_axi_out_V_AWLOCK),
    .m_axi_out_V_AWCACHE(grp_store_output_2_fu_128_m_axi_out_V_AWCACHE),
    .m_axi_out_V_AWPROT(grp_store_output_2_fu_128_m_axi_out_V_AWPROT),
    .m_axi_out_V_AWQOS(grp_store_output_2_fu_128_m_axi_out_V_AWQOS),
    .m_axi_out_V_AWREGION(grp_store_output_2_fu_128_m_axi_out_V_AWREGION),
    .m_axi_out_V_AWUSER(grp_store_output_2_fu_128_m_axi_out_V_AWUSER),
    .m_axi_out_V_WVALID(grp_store_output_2_fu_128_m_axi_out_V_WVALID),
    .m_axi_out_V_WREADY(m_axi_in_V_WREADY),
    .m_axi_out_V_WDATA(grp_store_output_2_fu_128_m_axi_out_V_WDATA),
    .m_axi_out_V_WSTRB(grp_store_output_2_fu_128_m_axi_out_V_WSTRB),
    .m_axi_out_V_WLAST(grp_store_output_2_fu_128_m_axi_out_V_WLAST),
    .m_axi_out_V_WID(grp_store_output_2_fu_128_m_axi_out_V_WID),
    .m_axi_out_V_WUSER(grp_store_output_2_fu_128_m_axi_out_V_WUSER),
    .m_axi_out_V_ARVALID(grp_store_output_2_fu_128_m_axi_out_V_ARVALID),
    .m_axi_out_V_ARREADY(1'b0),
    .m_axi_out_V_ARADDR(grp_store_output_2_fu_128_m_axi_out_V_ARADDR),
    .m_axi_out_V_ARID(grp_store_output_2_fu_128_m_axi_out_V_ARID),
    .m_axi_out_V_ARLEN(grp_store_output_2_fu_128_m_axi_out_V_ARLEN),
    .m_axi_out_V_ARSIZE(grp_store_output_2_fu_128_m_axi_out_V_ARSIZE),
    .m_axi_out_V_ARBURST(grp_store_output_2_fu_128_m_axi_out_V_ARBURST),
    .m_axi_out_V_ARLOCK(grp_store_output_2_fu_128_m_axi_out_V_ARLOCK),
    .m_axi_out_V_ARCACHE(grp_store_output_2_fu_128_m_axi_out_V_ARCACHE),
    .m_axi_out_V_ARPROT(grp_store_output_2_fu_128_m_axi_out_V_ARPROT),
    .m_axi_out_V_ARQOS(grp_store_output_2_fu_128_m_axi_out_V_ARQOS),
    .m_axi_out_V_ARREGION(grp_store_output_2_fu_128_m_axi_out_V_ARREGION),
    .m_axi_out_V_ARUSER(grp_store_output_2_fu_128_m_axi_out_V_ARUSER),
    .m_axi_out_V_RVALID(1'b0),
    .m_axi_out_V_RREADY(grp_store_output_2_fu_128_m_axi_out_V_RREADY),
    .m_axi_out_V_RDATA(16'd0),
    .m_axi_out_V_RLAST(1'b0),
    .m_axi_out_V_RID(1'd0),
    .m_axi_out_V_RUSER(1'd0),
    .m_axi_out_V_RRESP(2'd0),
    .m_axi_out_V_BVALID(m_axi_in_V_BVALID),
    .m_axi_out_V_BREADY(grp_store_output_2_fu_128_m_axi_out_V_BREADY),
    .m_axi_out_V_BRESP(m_axi_in_V_BRESP),
    .m_axi_out_V_BID(m_axi_in_V_BID),
    .m_axi_out_V_BUSER(m_axi_in_V_BUSER),
    .out_V_offset(out_V_offset),
    .fm_out_buff_V_address0(grp_store_output_2_fu_128_fm_out_buff_V_address0),
    .fm_out_buff_V_ce0(grp_store_output_2_fu_128_fm_out_buff_V_ce0),
    .fm_out_buff_V_q0(fm_out_buff_V_q0),
    .n(n_0_reg_92),
    .r(i_0_reg_104),
    .c(j_0_reg_116),
    .fsize(trunc_ln81_reg_309),
    .size(trunc_ln6_reg_341)
);

load_input_2 grp_load_input_2_fu_144(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_input_2_fu_144_ap_start),
    .ap_done(grp_load_input_2_fu_144_ap_done),
    .ap_idle(grp_load_input_2_fu_144_ap_idle),
    .ap_ready(grp_load_input_2_fu_144_ap_ready),
    .m_axi_in_V_AWVALID(grp_load_input_2_fu_144_m_axi_in_V_AWVALID),
    .m_axi_in_V_AWREADY(1'b0),
    .m_axi_in_V_AWADDR(grp_load_input_2_fu_144_m_axi_in_V_AWADDR),
    .m_axi_in_V_AWID(grp_load_input_2_fu_144_m_axi_in_V_AWID),
    .m_axi_in_V_AWLEN(grp_load_input_2_fu_144_m_axi_in_V_AWLEN),
    .m_axi_in_V_AWSIZE(grp_load_input_2_fu_144_m_axi_in_V_AWSIZE),
    .m_axi_in_V_AWBURST(grp_load_input_2_fu_144_m_axi_in_V_AWBURST),
    .m_axi_in_V_AWLOCK(grp_load_input_2_fu_144_m_axi_in_V_AWLOCK),
    .m_axi_in_V_AWCACHE(grp_load_input_2_fu_144_m_axi_in_V_AWCACHE),
    .m_axi_in_V_AWPROT(grp_load_input_2_fu_144_m_axi_in_V_AWPROT),
    .m_axi_in_V_AWQOS(grp_load_input_2_fu_144_m_axi_in_V_AWQOS),
    .m_axi_in_V_AWREGION(grp_load_input_2_fu_144_m_axi_in_V_AWREGION),
    .m_axi_in_V_AWUSER(grp_load_input_2_fu_144_m_axi_in_V_AWUSER),
    .m_axi_in_V_WVALID(grp_load_input_2_fu_144_m_axi_in_V_WVALID),
    .m_axi_in_V_WREADY(1'b0),
    .m_axi_in_V_WDATA(grp_load_input_2_fu_144_m_axi_in_V_WDATA),
    .m_axi_in_V_WSTRB(grp_load_input_2_fu_144_m_axi_in_V_WSTRB),
    .m_axi_in_V_WLAST(grp_load_input_2_fu_144_m_axi_in_V_WLAST),
    .m_axi_in_V_WID(grp_load_input_2_fu_144_m_axi_in_V_WID),
    .m_axi_in_V_WUSER(grp_load_input_2_fu_144_m_axi_in_V_WUSER),
    .m_axi_in_V_ARVALID(grp_load_input_2_fu_144_m_axi_in_V_ARVALID),
    .m_axi_in_V_ARREADY(m_axi_in_V_ARREADY),
    .m_axi_in_V_ARADDR(grp_load_input_2_fu_144_m_axi_in_V_ARADDR),
    .m_axi_in_V_ARID(grp_load_input_2_fu_144_m_axi_in_V_ARID),
    .m_axi_in_V_ARLEN(grp_load_input_2_fu_144_m_axi_in_V_ARLEN),
    .m_axi_in_V_ARSIZE(grp_load_input_2_fu_144_m_axi_in_V_ARSIZE),
    .m_axi_in_V_ARBURST(grp_load_input_2_fu_144_m_axi_in_V_ARBURST),
    .m_axi_in_V_ARLOCK(grp_load_input_2_fu_144_m_axi_in_V_ARLOCK),
    .m_axi_in_V_ARCACHE(grp_load_input_2_fu_144_m_axi_in_V_ARCACHE),
    .m_axi_in_V_ARPROT(grp_load_input_2_fu_144_m_axi_in_V_ARPROT),
    .m_axi_in_V_ARQOS(grp_load_input_2_fu_144_m_axi_in_V_ARQOS),
    .m_axi_in_V_ARREGION(grp_load_input_2_fu_144_m_axi_in_V_ARREGION),
    .m_axi_in_V_ARUSER(grp_load_input_2_fu_144_m_axi_in_V_ARUSER),
    .m_axi_in_V_RVALID(m_axi_in_V_RVALID),
    .m_axi_in_V_RREADY(grp_load_input_2_fu_144_m_axi_in_V_RREADY),
    .m_axi_in_V_RDATA(m_axi_in_V_RDATA),
    .m_axi_in_V_RLAST(m_axi_in_V_RLAST),
    .m_axi_in_V_RID(m_axi_in_V_RID),
    .m_axi_in_V_RUSER(m_axi_in_V_RUSER),
    .m_axi_in_V_RRESP(m_axi_in_V_RRESP),
    .m_axi_in_V_BVALID(1'b0),
    .m_axi_in_V_BREADY(grp_load_input_2_fu_144_m_axi_in_V_BREADY),
    .m_axi_in_V_BRESP(2'd0),
    .m_axi_in_V_BID(1'd0),
    .m_axi_in_V_BUSER(1'd0),
    .in_V_offset(in_V_offset),
    .fm_in_buff_V_address0(grp_load_input_2_fu_144_fm_in_buff_V_address0),
    .fm_in_buff_V_ce0(grp_load_input_2_fu_144_fm_in_buff_V_ce0),
    .fm_in_buff_V_we0(grp_load_input_2_fu_144_fm_in_buff_V_we0),
    .fm_in_buff_V_d0(grp_load_input_2_fu_144_fm_in_buff_V_d0),
    .n(n_0_reg_92),
    .r(i_0_reg_104),
    .c(j_0_reg_116),
    .fsize(trunc_ln81_reg_309),
    .size(size_reg_336)
);

compute_2 grp_compute_2_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_2_fu_160_ap_start),
    .ap_done(grp_compute_2_fu_160_ap_done),
    .ap_idle(grp_compute_2_fu_160_ap_idle),
    .ap_ready(grp_compute_2_fu_160_ap_ready),
    .fm_in_buff_V_address0(grp_compute_2_fu_160_fm_in_buff_V_address0),
    .fm_in_buff_V_ce0(grp_compute_2_fu_160_fm_in_buff_V_ce0),
    .fm_in_buff_V_q0(fm_in_buff_V_q0),
    .fm_in_buff_V_address1(grp_compute_2_fu_160_fm_in_buff_V_address1),
    .fm_in_buff_V_ce1(grp_compute_2_fu_160_fm_in_buff_V_ce1),
    .fm_in_buff_V_q1(fm_in_buff_V_q1),
    .fm_out_buff_V_address0(grp_compute_2_fu_160_fm_out_buff_V_address0),
    .fm_out_buff_V_ce0(grp_compute_2_fu_160_fm_out_buff_V_ce0),
    .fm_out_buff_V_we0(grp_compute_2_fu_160_fm_out_buff_V_we0),
    .fm_out_buff_V_d0(grp_compute_2_fu_160_fm_out_buff_V_d0)
);

conv_mul_32s_32s_tde #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
conv_mul_32s_32s_tde_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(h),
    .din1(h),
    .ce(1'b1),
    .dout(grp_fu_166_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_2_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_compute_2_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_compute_2_fu_160_ap_ready == 1'b1)) begin
            grp_compute_2_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_input_2_fu_144_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln80_fu_271_p2 == 1'd1))) begin
            grp_load_input_2_fu_144_ap_start_reg <= 1'b1;
        end else if ((grp_load_input_2_fu_144_ap_ready == 1'b1)) begin
            grp_load_input_2_fu_144_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_output_2_fu_128_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_store_output_2_fu_128_ap_start_reg <= 1'b1;
        end else if ((grp_store_output_2_fu_128_ap_ready == 1'b1)) begin
            grp_store_output_2_fu_128_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln78_fu_247_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        i_0_reg_104 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln80_fu_271_p2 == 1'd0))) begin
        i_0_reg_104 <= i_fu_276_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln79_fu_256_p2 == 1'd1))) begin
        j_0_reg_116 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state13) & (grp_store_output_2_fu_128_ap_done == 1'b1))) begin
        j_0_reg_116 <= j_reg_365;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln79_fu_256_p2 == 1'd0))) begin
        n_0_reg_92 <= n_fu_261_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        n_0_reg_92 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        j_reg_365 <= j_fu_282_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        lshr_ln79_1_reg_299 <= {{sub_ln79_fu_180_p2[31:1]}};
        lshr_ln79_2_reg_304 <= {{lshr_ln79_2_fu_196_p1[31:1]}};
        tmp_reg_294 <= tmp_fu_172_p1[32'd31];
        trunc_ln81_reg_309 <= trunc_ln81_fu_206_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln79_reg_315 <= select_ln79_fu_222_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        size_reg_336 <= size_fu_229_p1;
        trunc_ln6_reg_341 <= {{grp_fu_166_p2[15:2]}};
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state6) & (icmp_ln78_fu_247_p2 == 1'd0)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln78_fu_247_p2 == 1'd0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm_in_buff_V_address0 = grp_compute_2_fu_160_fm_in_buff_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        fm_in_buff_V_address0 = grp_load_input_2_fu_144_fm_in_buff_V_address0;
    end else begin
        fm_in_buff_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm_in_buff_V_ce0 = grp_compute_2_fu_160_fm_in_buff_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        fm_in_buff_V_ce0 = grp_load_input_2_fu_144_fm_in_buff_V_ce0;
    end else begin
        fm_in_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm_in_buff_V_ce1 = grp_compute_2_fu_160_fm_in_buff_V_ce1;
    end else begin
        fm_in_buff_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        fm_in_buff_V_we0 = grp_load_input_2_fu_144_fm_in_buff_V_we0;
    end else begin
        fm_in_buff_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm_out_buff_V_address0 = grp_compute_2_fu_160_fm_out_buff_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        fm_out_buff_V_address0 = grp_store_output_2_fu_128_fm_out_buff_V_address0;
    end else begin
        fm_out_buff_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm_out_buff_V_ce0 = grp_compute_2_fu_160_fm_out_buff_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        fm_out_buff_V_ce0 = grp_store_output_2_fu_128_fm_out_buff_V_ce0;
    end else begin
        fm_out_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        fm_out_buff_V_we0 = grp_compute_2_fu_160_fm_out_buff_V_we0;
    end else begin
        fm_out_buff_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state8) & (icmp_ln80_fu_271_p2 == 1'd1)))) begin
        m_axi_in_V_ARVALID = grp_load_input_2_fu_144_m_axi_in_V_ARVALID;
    end else begin
        m_axi_in_V_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        m_axi_in_V_AWVALID = grp_store_output_2_fu_128_m_axi_out_V_AWVALID;
    end else begin
        m_axi_in_V_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        m_axi_in_V_BREADY = grp_store_output_2_fu_128_m_axi_out_V_BREADY;
    end else begin
        m_axi_in_V_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state8) & (icmp_ln80_fu_271_p2 == 1'd1)))) begin
        m_axi_in_V_RREADY = grp_load_input_2_fu_144_m_axi_in_V_RREADY;
    end else begin
        m_axi_in_V_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        m_axi_in_V_WVALID = grp_store_output_2_fu_128_m_axi_out_V_WVALID;
    end else begin
        m_axi_in_V_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln78_fu_247_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln79_fu_256_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln80_fu_271_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((grp_load_input_2_fu_144_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_compute_2_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_store_output_2_fu_128_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_compute_2_fu_160_ap_start = grp_compute_2_fu_160_ap_start_reg;

assign grp_load_input_2_fu_144_ap_start = grp_load_input_2_fu_144_ap_start_reg;

assign grp_store_output_2_fu_128_ap_start = grp_store_output_2_fu_128_ap_start_reg;

assign i_fu_276_p2 = (i_0_reg_104 + 16'd13);

assign icmp_ln78_fu_247_p2 = (($signed(zext_ln78_fu_243_p1) < $signed(ch)) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_256_p2 = (($signed(zext_ln79_fu_252_p1) < $signed(select_ln79_reg_315)) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_271_p2 = (($signed(zext_ln80_fu_267_p1) < $signed(select_ln79_reg_315)) ? 1'b1 : 1'b0);

assign j_fu_282_p2 = (j_0_reg_116 + 16'd13);

assign lshr_ln79_2_fu_196_p1 = h;

assign m_axi_in_V_ARADDR = grp_load_input_2_fu_144_m_axi_in_V_ARADDR;

assign m_axi_in_V_ARBURST = grp_load_input_2_fu_144_m_axi_in_V_ARBURST;

assign m_axi_in_V_ARCACHE = grp_load_input_2_fu_144_m_axi_in_V_ARCACHE;

assign m_axi_in_V_ARID = grp_load_input_2_fu_144_m_axi_in_V_ARID;

assign m_axi_in_V_ARLEN = grp_load_input_2_fu_144_m_axi_in_V_ARLEN;

assign m_axi_in_V_ARLOCK = grp_load_input_2_fu_144_m_axi_in_V_ARLOCK;

assign m_axi_in_V_ARPROT = grp_load_input_2_fu_144_m_axi_in_V_ARPROT;

assign m_axi_in_V_ARQOS = grp_load_input_2_fu_144_m_axi_in_V_ARQOS;

assign m_axi_in_V_ARREGION = grp_load_input_2_fu_144_m_axi_in_V_ARREGION;

assign m_axi_in_V_ARSIZE = grp_load_input_2_fu_144_m_axi_in_V_ARSIZE;

assign m_axi_in_V_ARUSER = grp_load_input_2_fu_144_m_axi_in_V_ARUSER;

assign m_axi_in_V_AWADDR = grp_store_output_2_fu_128_m_axi_out_V_AWADDR;

assign m_axi_in_V_AWBURST = grp_store_output_2_fu_128_m_axi_out_V_AWBURST;

assign m_axi_in_V_AWCACHE = grp_store_output_2_fu_128_m_axi_out_V_AWCACHE;

assign m_axi_in_V_AWID = grp_store_output_2_fu_128_m_axi_out_V_AWID;

assign m_axi_in_V_AWLEN = grp_store_output_2_fu_128_m_axi_out_V_AWLEN;

assign m_axi_in_V_AWLOCK = grp_store_output_2_fu_128_m_axi_out_V_AWLOCK;

assign m_axi_in_V_AWPROT = grp_store_output_2_fu_128_m_axi_out_V_AWPROT;

assign m_axi_in_V_AWQOS = grp_store_output_2_fu_128_m_axi_out_V_AWQOS;

assign m_axi_in_V_AWREGION = grp_store_output_2_fu_128_m_axi_out_V_AWREGION;

assign m_axi_in_V_AWSIZE = grp_store_output_2_fu_128_m_axi_out_V_AWSIZE;

assign m_axi_in_V_AWUSER = grp_store_output_2_fu_128_m_axi_out_V_AWUSER;

assign m_axi_in_V_WDATA = grp_store_output_2_fu_128_m_axi_out_V_WDATA;

assign m_axi_in_V_WID = grp_store_output_2_fu_128_m_axi_out_V_WID;

assign m_axi_in_V_WLAST = grp_store_output_2_fu_128_m_axi_out_V_WLAST;

assign m_axi_in_V_WSTRB = grp_store_output_2_fu_128_m_axi_out_V_WSTRB;

assign m_axi_in_V_WUSER = grp_store_output_2_fu_128_m_axi_out_V_WUSER;

assign n_fu_261_p2 = (n_0_reg_92 + 16'd4);

assign select_ln79_fu_222_p3 = ((tmp_reg_294[0:0] === 1'b1) ? sub_ln79_1_fu_213_p2 : zext_ln79_2_fu_219_p1);

assign size_fu_229_p1 = grp_fu_166_p2[15:0];

assign sub_ln79_1_fu_213_p2 = (32'd0 - zext_ln79_1_fu_210_p1);

assign sub_ln79_fu_180_p1 = h;

assign sub_ln79_fu_180_p2 = ($signed(32'd0) - $signed(sub_ln79_fu_180_p1));

assign tmp_fu_172_p1 = h;

assign trunc_ln81_fu_206_p0 = h;

assign trunc_ln81_fu_206_p1 = trunc_ln81_fu_206_p0[15:0];

assign zext_ln78_fu_243_p1 = n_0_reg_92;

assign zext_ln79_1_fu_210_p1 = lshr_ln79_1_reg_299;

assign zext_ln79_2_fu_219_p1 = lshr_ln79_2_reg_304;

assign zext_ln79_fu_252_p1 = i_0_reg_104;

assign zext_ln80_fu_267_p1 = j_0_reg_116;

endmodule //maxpool
